export const TEAM_A = "A"
export const TEAM_B = "B"

export const PLAYER_A1 = "a1"
export const PLAYER_A2 = "a2"
export const PLAYER_B1 = "b1"
export const PLAYER_B2 = "b2"

export const EVENT_GAME_START = "Game Start"
export const EVENT_POINT = "Point"
export const EVENT_SERVER_CHANGE = "Server Change"
export const EVENT_SIDE_OUT = "Side Out"
export const EVENT_TIMEOUT_A = "Timeout A"
export const EVENT_TIMEOUT_B = "Timeout B"
export const EVENT_WIN = "Win"

export const LOG_CLASS_MAP = {
  [EVENT_POINT]: "log-point",
  [EVENT_SERVER_CHANGE]: "log-change",
  [EVENT_SIDE_OUT]: "log-sideout",
  [EVENT_GAME_START]: "log-start",
  [EVENT_WIN]: "log-win",
  [EVENT_TIMEOUT_A]: "log-timeout",
  [EVENT_TIMEOUT_B]: "log-timeout",
}

export const DEFAULT_GAME_POINT = 11
export const DEFAULT_TIMEOUT_LIMIT = 2
export const WIN_MARGIN = 2
export const INITIAL_SERVER_NUMBER = 2

export const DEFAULT_TEAM_A_NAME = "TEAM A"
export const DEFAULT_TEAM_B_NAME = "TEAM B"
export const DEFAULT_PLAYER_NAMES = {
  [PLAYER_A1]: "P1",
  [PLAYER_A2]: "P2",
  [PLAYER_B1]: "P3",
  [PLAYER_B2]: "P4",
}

export const STORAGE_KEY = "pickleball_match"
export const ADMIN_CODE = "admin"

export const COURT_OFFSET = "15%"
export const POSITION_AUTO = "auto"

export const MAX_TIMEOUT_DOTS = 3

export const PDF_HEADER_COLOR = [34, 197, 94]
export const PDF_LOG_HEADER_COLOR = [59, 130, 246]
export const PDF_FILENAME = "pickleball_match_report.pdf"
export const PDF_FOOTER_TEXT = "Generated by Pickleball Scorer by Zyl Arpon"
